- hosts: localhost
  vars_files:
  - properties/ds_delete_input.yml
  - properties/credential-vault 

  environment:
    no_proxy: "{{ no_proxy_env }}"

  tasks:
    - name: Mount VMFS datastores to ESXi
      vmware_datastore_san_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datastore_name: '{{ vcenter_datastore }}'
        validate_certs: False
      delegate_to: localhost
      register: datastoreFacts

    - set_fact:
        datastore_wwn: "{{ item.wwn[0] | upper }}"
      with_items: "{{ datastoreFacts.datastores }}"

    - fail:
        msg: "Unable to find 3PAR volume wwn of the datastore {{ vcenter_datastore }}"
      when: datastore_wwn is not defined

    - name: Unmount and delete the VMFS datastores from vCenter
      vmware_host_datastore_san:
          hostname: '{{ vcenter_hostname }}'
          username: '{{ vcenter_username }}'
          password: '{{ vcenter_password }}'
          datastore_name: '{{ vcenter_datastore }}'
          volume_device_name: '{{ datastore_wwn }}'
          esxi_hostname: '{{ esxi_hostname }}'
          validate_certs: False
          state: absent
      delegate_to: localhost

    - name: "Find all the storage volumes"
      hpe3par_volume_facts:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
      register: allVolumes

    - set_fact:
        storage_wwn: "{{ item.wwn }}"
        storage_name : "{{ item.name }}"
      with_items: "{{ allVolumes.volumes }}"
      when: datastore_wwn == item.wwn

    - fail:
        msg: "Fail to find any volume with {{ datastore_wwn }}"
      when: storage_wwn is not defined

    - name: Delete VLUN
      hpe3par_vlun:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        state: unexport_volume_from_hostset
        volume_name: "{{ storage_name }}"
        host_set_name: "{{ storage_cluster }}"

    - name: Delete Volume "{{ storage_name }}"
      hpe3par_volume:
        storage_system_ip: "{{ storage_system_ip }}"
        storage_system_username: "{{ storage_system_username }}"
        storage_system_password: "{{ storage_system_password }}"
        state: absent
        volume_name: "{{ storage_name }}"
